### ISSUE TITLE
can not upload

### ISSUE THREAD

**Issue by liamxg** [nextstrain/auspice.us#78]
<img width="1340" alt="image" src="https://github.com/nextstrain/auspice.us/assets/46078579/5004d994-7e0b-4846-adda-acfefab8ef43">

**Comment by AngieHinrichs** [comment]
@liamxg can you attach the files that you dropped onto auspice.us?

**Comment by AngieHinrichs** [comment]
You should run the Augur pipeline on the sequences and metadata -- the output of Augur is the input for Auspice.  I don't have much experience with the Augur pipeline because I run the UShER tools instead.  But the Nextstrain team has written excellent documentation for how to run Augur:

https://docs.nextstrain.org/projects/augur/en/stable/

And Nextstrain has a great forum and user community for asking questions about Augur and Auspice:

https://discussion.nextstrain.org/

**Comment by victorlin** [comment]
Thanks @AngieHinrichs for those links!

@liamxg for your example, assuming it is for SARS-CoV-2 sequences, you may be interested in our [SARS-CoV-2 workflow tutorials](https://docs.nextstrain.org/projects/ncov/en/latest/tutorial/intro.html), specifically the one titled **Run using custom data** which directly uses GISAID's **Input for the Augur pipeline** download option.

**Comment by AngieHinrichs** [comment]
> Dear @AngieHinrichs, Could auspice view the `ncov_idaho_tip-frequencies.json` file generated with `ncov_idaho.json` file from nextstrain pipeline?

I don't know -- I have not worked with tip-frequencies files before.
